# Base component API configuration
__merge__: /src/api/comp_process_dataset.yaml

# Component configuration
name: process_dataset

# Script configuration
resources:
  - type: python_script
    path: script.py
  - path: /common/helper_functions/subset_h5ad_by_format.py

# Platform configuration
engines:
  - type: docker
    image: openproblems/base_python:1
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, midcpu, midtime]
